In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
plt.style.use('seaborn')

In [2]:
df = pd.read_csv(r"C:\Users\Suwani Gunasekara\OneDrive\Documents\Sem 7 ML\winequality-white.csv")

In [3]:
df.head()

WineWhiteSerial  fixed acidity  volatile acidity  citric acid  \
0                1            7.0              0.27         0.36   
1                2            6.3              0.30         0.34   
2                3            8.1              0.28         0.40   
3                4            7.2              0.23         0.32   
4                5            7.2              0.23         0.32   

   residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
0            20.7      0.045                 45.0                 170.0   
1             1.6      0.049                 14.0                 132.0   
2             6.9      0.050                 30.0                  97.0   
3             8.5      0.058                 47.0                 186.0   
4             8.5      0.058                 47.0                 186.0   

   density    pH  sulphates  alcohol  quality  
0   1.0010  3.00       0.45      8.8        6  
1   0.9940  3.30       0.49      9.5        6  
2   0.9951  3.26       0.44     10.1        6  
3   0.9956  3.19       0.40      9.9        6  
4   0.9956  3.19       0.40      9.9        6

In [4]:
df.drop('WineWhiteSerial', inplace=True, axis=1)

In [5]:
df['quality_'] = np.where(df['quality'] > 6, 1,0)

In [24]:
df.head()

Ones  fixed acidity  volatile acidity  citric acid  residual sugar  \
0     1            7.0              0.27         0.36            20.7   
1     1            6.3              0.30         0.34             1.6   
2     1            8.1              0.28         0.40             6.9   
3     1            7.2              0.23         0.32             8.5   
4     1            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality_  
0       0.45      8.8         0  
1       0.49      9.5         0  
2       0.44     10.1         0  
3       0.40      9.9         0  
4       0.40      9.9         0

In [7]:
df.drop('quality', inplace=True, axis=1)

In [23]:
#df.to_csv(r"C:\Users\Suwani Gunasekara\OneDrive\Documents\Sem 7 ML\winequality-white_onezero.csv")

In [31]:
df = pd.read_csv(r"C:\Users\Suwani Gunasekara\OneDrive\Documents\Sem 7 ML\winequality-white_onezero.csv")

In [32]:
# why do we need the range to be between 0 and 1? --> Because it is a probability (?) CHECK!!!!
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

In [33]:
# This is the error function. We need to minimize this
def cost(theta, X, y):
    theta = np.matrix(theta)
    X = np.matrix(X)
    y = np.matrix(y)
    first = np.multiply(-y, np.log(sigmoid(X * theta.T)))
    second = np.multiply((1 - y), np.log(1 - sigmoid(X * theta.T)))
    return np.sum(first - second) / (len(X))

In [34]:
# add a ones column - this makes the matrix multiplication work out easier
df.insert(0, 'Ones', 1)

# set X (training data) and y (target variable)
cols = df.shape[1]
X = df.iloc[:,0:cols-1]
y = df.iloc[:,cols-1:cols]

# convert to numpy arrays and initalize the parameter array theta
X = np.array(X.values)
y = np.array(y.values)
theta = np.zeros(12)

In [35]:
y

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]], dtype=int64)

In [36]:
def gradient(theta, X, y):
    theta = np.matrix(theta)
    X = np.matrix(X)
    y = np.matrix(y)
    
    parameters = int(theta.ravel().shape[1])
    grad = np.zeros(parameters)
    
    error = sigmoid(X * theta.T) - y
    
    for i in range(parameters):
        term = np.multiply(error, X[:,i])
        grad[i] = np.sum(term) / len(X)
    
    return grad

In [37]:
gradient(theta, X, y)

array([2.83585137e-01, 1.97197325e+00, 8.16950796e-02, 9.65322581e-02,
       2.05703859e+00, 1.46277052e-02, 1.01768069e+01, 4.20753879e+01,
       2.82240985e-01, 8.98330951e-01, 1.36685382e-01, 2.78653668e+00])

In [15]:
import scipy.optimize as opt
result = opt.fmin_tnc(func=cost, x0=theta, fprime=gradient, args=(X, y))
result

(array([-7.49945140e+00,  8.73560227e-02, -3.96055740e+00, -8.33058411e-01,
         6.24470363e-02, -1.79456761e+01,  1.30944492e-02, -3.22333739e-03,
        -7.66831734e+00,  1.48248809e+00,  1.23404676e+00,  8.83081194e-01]),
 120,
 3)

In [16]:
def predict(theta, X):
    probability = sigmoid(X * theta.T)
    return [1 if x >= 0.5 else 0 for x in probability]

In [22]:
theta_min = np.matrix(result[0])
predictions = predict(theta_min, X)
correct = [1 if ((a == 1 and b == 1) or (a == 0 and b == 0)) else 0 for (a, b) in zip(predictions, y)]
accuracy = (sum(map(int, correct)) / len(correct))
print (accuracy)

0.8007349938750511


In [20]:
sum(map(int,correct))

3922

In [21]:
len(correct)

4898